### ISSUE TITLE
Task 'runForcedAlignment' not found in root project 'gradle-marytts-kaldi-mfa-plugin'

### ISSUE THREAD

**Issue by mbarnig** [marytts/gradle-marytts-kaldi-mfa-plugin#14]
Above error message when running ./gradlew runForcedAlignment.
./gradlew tasks --all  doesn't show the runForcedAlignment task.

**Comment by psibre** [comment]
This is for the *source code* of the Gradle plugin. To *use* it, apply the plugin to a *different* project, as documented in the README.
See also https://docs.gradle.org/current/userguide/plugins.html.
